version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        restart: always
    node-app:
        build: .
        env_file:
            - ./.env
        depends_on:
            - postgres

    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=deger
            - POSTGRES_DB=chatdb
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 5431:5432
        # ports:
        #     - 27018:27017
        # This is for connection with db manage tools. Remove for security

volumes:
    postgres-data: